name: IDrop
description: Mobile application - IDrop NFC

publish_to: 'none'

version: 1.2.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  connectivity: ^3.0.3
  shared_preferences: ^2.0.5
  uuid: 3.0.6
  select_form_field: ^2.2.0
  persistent_bottom_nav_bar: ^3.1.0
  flutter_secure_storage: ^6.0.0
  http: ^0.13.0
  form_validator: ">=0.1.1 <2.0.0"
  flutter_spinkit: ^5.0.0
  nfc_in_flutter: ^2.0.5
  after_init: ^0.1.2
  adaptive_dialog: ^0.10.0+5
  url_launcher: ^6.0.2
  image_picker: ^0.8.2
  http_parser: ^4.0.0
  flutter_launcher_icons: ^0.9.0
  permission_handler: ^10.0.0
  plugin_platform_interface: ^2.0.0
  image_picker_platform_interface: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/websites/