name: nfc_mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^4.3.3
  persistent_bottom_nav_bar: ^3.1.0
  fluttertoast: ^7.1.6
  flutter_launcher_icons: "^0.8.0"
  flutter:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app-icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/icons/