name: idrop
description: Mobile application - IDrop NFC

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  persistent_bottom_nav_bar: ^3.1.0
  flutter_secure_storage: ^3.3.5
  http: ^0.12.2
  form_validator: ">=0.1.1 <2.0.0"
  flutter_spinkit: "^4.1.2"
  fluttertoast: ^7.1.6
  nfc_in_flutter: ^2.0.5
  pull_to_refresh: <=1.6.3
  after_init: ^0.1.2
  adaptive_dialog: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/