final Map<String, dynamic> brandKeys = {
  'phoneNumber': 'Phone number',
  'instagramAccount': 'Instagram',
  'twitterAccount': 'Twitter',
  'facebookAccount': 'Facebook',
  'linkedinAccount': 'LinkedIn',
  'whatsAppNumber': 'WhatsApp',
  'publicEmail': 'E-mail',
  'youtubeAccount': 'YouTube',
  'soundcloudAccount': 'SoundCloud',
  'tiktokAccount': 'TikTok',
  'spotifyAccount': 'Spotify',
  'appleMusicAccount': 'Apple Music',
  'cashAppAccount': 'Cash App',
  'venmoAccount': 'Venmo',
  'paypalAccount': 'PayPal',
  'twitchAccount': 'Twitch',
  'snapchatName': 'Snapchat',
  'website': 'Website',
};
